# **Theoretical Questions:**

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

---
NumPy, short for Numerical Python, is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and a wide variety of mathematical functions to operate on these data structures. Here are some key points regarding its purpose, advantages, and how it enhances Python's capabilities for numerical operations.

Purpose of NumPy
Efficient Data Handling:

NumPy provides a robust data structure called ndarray, which allows for efficient storage and manipulation of large datasets, especially in multi-dimensional formats.
Mathematical Operations:

It includes a range of mathematical functions to perform operations on arrays and matrices, making it ideal for scientific computing and data analysis.
Interoperability:

NumPy integrates seamlessly with other scientific libraries like SciPy, pandas, and Matplotlib, forming a comprehensive ecosystem for data analysis and visualization.
Advantages of NumPy
Performance:

NumPy operations are significantly faster than traditional Python lists, primarily due to its implementation in C and the ability to utilize optimized libraries for numerical computations (like BLAS and LAPACK).
Vectorized operations allow for element-wise operations on entire arrays without explicit loops, reducing the execution time.
Memory Efficiency:

NumPy arrays consume less memory than Python lists because they are densely packed in memory and have a fixed data type, which enhances performance and reduces memory usage.
Convenience:

NumPy offers a wide variety of built-in functions for linear algebra, statistics, and random number generation, which simplifies complex numerical computations.
It supports advanced indexing and slicing, making data manipulation more intuitive.
Rich Functionality:

NumPy provides functions for mathematical operations (like sin, cos, mean, std), linear algebra (like matrix multiplication, determinant, and eigenvalues), and Fourier transforms, among others.
Broadcasting:

NumPy supports broadcasting, a powerful mechanism that allows operations between arrays of different shapes, facilitating efficient and concise coding.
Enhancing Python's Numerical Capabilities
Array and Matrix Operations:

NumPy's ndarray allows for multi-dimensional array operations that are not natively supported by Python lists. This capability makes it easy to perform mathematical operations directly on data structures without looping through elements.
Linear Algebra Support:

NumPy provides extensive functions for linear algebra, making it easier to solve systems of equations, perform matrix decompositions, and conduct eigenvalue analysis.
Statistical Functions:

Built-in statistical functions allow for easy computation of means, medians, variances, and other statistical measures directly on arrays.
Integration with Other Libraries:

Many scientific libraries in Python (like SciPy, pandas, and scikit-learn) are built on top of NumPy, enabling users to leverage its array structure and mathematical functions across various domains, from data analysis to machine learning.


2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

---
Both np.mean() and np.average() are functions in NumPy used to compute the average of array elements, but they have some important differences in functionality and flexibility. Here’s a comparison:

np.mean()
Purpose: Computes the arithmetic mean (average) of the elements in an array.
Parameters:
array: Input array.
axis: Axis along which the mean is computed. Default is None, which computes the mean of the flattened array.
dtype: Data type used in the calculation.
out: Alternative output array to store the result.
Return Value: Returns a scalar value (or an array if an axis is specified) representing the mean of the input array.
np.average()
Purpose: Computes the weighted average of the elements in an array, allowing for more flexibility.

Parameters:
array: Input array.
weights: An optional array of the same shape as array that specifies the weight for each element. If not specified, all elements are considered equally weighted.
axis: Axis along which the average is computed. Default is None.
returned: If True, it returns a tuple of the average and the sum of the weights.
Return Value: Returns the weighted average (or unweighted average if weights are not provided). It can also return the sum of the weights if returned=True.
Key Differences
Weights:

np.mean(): Always computes the unweighted average.
np.average(): Can compute weighted averages, making it more versatile in certain situations.
Functionality:

np.mean(): Simpler and more straightforward for basic averaging tasks.
np.average(): More flexible, particularly useful when dealing with data that requires weighting.
Performance:

Both functions are optimized for performance, but since np.mean() is less complex, it may be slightly faster when only computing the average without weights.
When to Use Each
Use np.mean():

When you simply need to compute the average of an array without any additional complexity.
For straightforward averaging tasks, such as analyzing data distributions.
Use np.average():

When you need to compute a weighted average, especially when some values in the dataset are more significant than others.
For cases where you have associated weights for each element (e.g., when averaging test scores based on the importance of each test).


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

---

Reversing a NumPy array can be accomplished using various methods, depending on whether you're dealing with 1D or 2D arrays and the specific axis along which you want to reverse the array. Here’s a breakdown of how to reverse NumPy arrays along different axes, along with examples.

Reversing a 1D Array
For a 1D array, reversing can be done simply by slicing. Here’s how to do it:

Method 1: Slicing
You can reverse a 1D array by using slicing with a step of -1.
Reversing a 2D Array
For 2D arrays, you can reverse along specific axes using similar slicing techniques or the np.flip() function.

Method 2: Slicing for 2D Arrays
To reverse a 2D array along specific axes, you can specify the axis in the slicing notation.

Method 3: Using np.flip()
The np.flip() function can also be used to reverse an array along a specified axis.

In [1]:
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reversing the 1D array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D Array:", arr_1d)
print("Reversed 1D Array:", reversed_arr_1d)
# Creating a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reversing along the first axis (rows)
reversed_rows = arr_2d[::-1]

# Reversing along the second axis (columns)
reversed_cols = arr_2d[:, ::-1]

print("Original 2D Array:\n", arr_2d)
print("Reversed 2D Array (rows):\n", reversed_rows)
print("Reversed 2D Array (columns):\n", reversed_cols)
# Reversing along the first axis (rows)
flipped_rows = np.flip(arr_2d, axis=0)

# Reversing along the second axis (columns)
flipped_cols = np.flip(arr_2d, axis=1)

print("Flipped 2D Array (rows):\n", flipped_rows)
print("Flipped 2D Array (columns):\n", flipped_cols)

Original 1D Array: [1 2 3 4 5]
Reversed 1D Array: [5 4 3 2 1]
Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D Array (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D Array (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flipped 2D Array (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Flipped 2D Array (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.
Importance of Data Types
Memory Management:

Memory Size: Different data types require different amounts of memory. For example, an int8 uses 1 byte, while an int64 uses 8 bytes. Choosing the right data type can significantly reduce memory consumption, especially when dealing with large datasets.
Storage Efficiency: Using the most appropriate data type allows for efficient storage of large arrays. For example, if you know your data values will always be less than 256, using uint8 instead of int32 saves memory.
Performance:

Speed of Operations: NumPy operations are optimized for specific data types. For instance, operations on integers may be faster than those on floating-point numbers due to lower complexity in arithmetic.
Vectorization: NumPy’s ability to perform vectorized operations relies heavily on data types. Using homogeneous data types allows for faster computation as NumPy can leverage optimized algorithms for those types.
Precision:

Data Accuracy: The choice of data type affects the precision of numerical computations. For example, using float32 instead of float64 can lead to loss of precision in calculations that require high accuracy, such as scientific computations.
Compatibility:

Interoperability: Data types influence compatibility with other libraries and data formats. For instance, certain functions in libraries like pandas or machine learning libraries may expect specific data types for optimal functionality.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

---
In NumPy, ndarrays (n-dimensional arrays) are the core data structure used for numerical computations. They provide a powerful way to store and manipulate large datasets efficiently. Here’s a detailed explanation of ndarrays, their key features, and how they differ from standard Python lists.

Definition of ndarrays
An ndarray is a homogeneous, multidimensional array that allows for efficient storage and manipulation of numerical data. It is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.

Key Features of ndarrays
Homogeneity:

All elements in an ndarray must be of the same data type (e.g., all integers, all floats). This uniformity allows for optimized performance and memory efficiency.
Multidimensionality:

ndarrays can have any number of dimensions (1D, 2D, 3D, etc.). This makes them suitable for representing vectors, matrices, and higher-dimensional data structures.
Memory Efficiency:

ndarrays are implemented in C and can use contiguous blocks of memory, making them more efficient than Python lists, especially for large datasets.
Performance:

NumPy operations on ndarrays are highly optimized. Element-wise operations, mathematical functions, and linear algebra computations are performed using efficient algorithms, often leading to faster execution times compared to native Python loops.
Broadcasting:

NumPy supports broadcasting, which allows operations between arrays of different shapes and sizes. This feature simplifies code and enables vectorized operations without the need for explicit loops.
Rich Functionality:

NumPy provides a vast library of mathematical functions that can be applied to ndarrays, including linear algebra, statistics, and Fourier transforms.
Flexible Reshaping:

You can easily change the shape of an ndarray without changing its data, which is useful for data preprocessing and analysis.
Indexing and Slicing:

ndarrays support advanced indexing and slicing, allowing for easy selection and modification of subsets of data.
Differences from Standard Python Lists
Homogeneity vs. Heterogeneity:

ndarrays: Must contain elements of the same type.
Python Lists: Can contain elements of different types (e.g., integers, strings, other lists).
Dimensionality:

ndarrays: Can be n-dimensional.
Python Lists: Primarily 1D, but can be nested to create multi-dimensional structures, which can be less efficient and harder to manage.
Performance:

ndarrays: Optimized for performance and memory efficiency; faster for numerical computations.
Python Lists: Slower for large datasets and computational tasks, as they require more overhead due to their flexibility.
Functionality:

ndarrays: Come with a rich set of built-in mathematical functions and capabilities for numerical analysis.
Python Lists: Lack built-in support for mathematical operations and require explicit loops for computations.
Broadcasting:

ndarrays: Support broadcasting, allowing operations on arrays of different shapes.
Python Lists: Do not support broadcasting natively, requiring manual handling for operations involving different sizes.


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.



---
NumPy arrays provide significant performance benefits over standard Python lists, especially for large-scale numerical operations. Here’s an analysis of these benefits:

1. Memory Efficiency
Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory, which reduces overhead and improves cache locality. This means that when an array is processed, adjacent elements are likely to be in the cache, leading to faster access times.

Fixed Data Type: NumPy arrays require all elements to be of the same type, which allows for more efficient use of memory. In contrast, Python lists can hold elements of different types, which incurs additional overhead for type management.

2. Performance on Operations
Vectorized Operations: NumPy allows for vectorized operations, which enable batch processing of data without the need for explicit loops in Python. This leads to significant speed improvements since operations are executed at a lower level (in C) rather than in the Python interpreter.

Element-wise Operations: Operations on NumPy arrays are performed element-wise, allowing for concise and fast computations. For example, adding two large arrays together is done in a single command, while equivalent operations with lists would require looping through each element.

3. Optimized Mathematical Functions
Built-in Functions: NumPy provides a wide array of optimized mathematical functions that are specifically designed for array operations. These functions are implemented in C and are highly optimized for performance, enabling faster calculations compared to custom Python functions.

Broadcasting: NumPy supports broadcasting, which allows for operations on arrays of different shapes without requiring explicit replication of data. This reduces memory usage and improves performance, especially when working with matrices or higher-dimensional data.

4. Parallelization and SIMD Instructions
Low-level Optimizations: NumPy leverages low-level libraries like BLAS and LAPACK, which are optimized for performance on modern CPUs. These libraries can take advantage of SIMD (Single Instruction, Multiple Data) instructions, allowing for parallel processing of array elements.
5. Reduced Overhead
Fewer Function Calls: Operations on NumPy arrays typically involve fewer function calls compared to list operations. This reduction in overhead leads to faster execution times, especially when performing numerous calculations.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

---
In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. Both functions allow for combining arrays into a larger array, but they do so along different axes. Here’s a detailed comparison of the two functions along with examples demonstrating their usage.

1. vstack()
Purpose: Stacks arrays vertically (row-wise).
Axis: Stacks along the first axis (axis 0).
Usage: Ideal for combining arrays that you want to stack on top of each other.
2. hstack()
Purpose: Stacks arrays horizontally (column-wise).
Axis: Stacks along the second axis (axis 1).
Usage: Suitable for combining arrays that you want to place side by side.


In [2]:
#Example of vstack()
import numpy as np

# Creating two 2D arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Using vstack to stack the arrays vertically
result_vstack = np.vstack((arr1, arr2))

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nResult of vstack:")
print(result_vstack)
#Example on hstack()
import numpy as np
result_hstack = np.hstack((arr1, arr2))

print("\nResult of hstack:")
print(result_hstack)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Result of vstack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result of hstack:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.


---

In NumPy, fliplr() and flipud() are functions used to flip arrays, but they do so along different axes. Here’s an explanation of their differences and effects on various array dimensions.

1. fliplr()
Purpose: Flips an array from left to right (horizontally).
Axis: Operates along the second axis (axis 1), effectively reversing the order of the columns.
Usage: This function is useful for manipulating 2D arrays (matrices) where you want to reflect the data along the vertical axis.

2. flipud()
Purpose: Flips an array from up to down (vertically).
Axis: Operates along the first axis (axis 0), effectively reversing the order of the rows.
Usage: This function is useful for manipulating 2D arrays (matrices) where you want to reflect the data along the horizontal axis.
Effects on Various Array Dimensions

1.2D Arrays

  List item
  List item

fliplr(): Flips columns, reversing the order of elements in each row.
flipud(): Flips rows, reversing the order of elements in each column.

2.1D Arrays:
Both functions are not applicable since they require at least a 2D array. However, using them on a 1D array will result in an error.

3.Higher-Dimensional Arrays:
For arrays with more than 2 dimensions, these functions only operate on the first two dimensions (i.e., they will flip the 2D "slices" of the higher-dimensional array).
For example, for a 3D array, fliplr() will flip each 2D slice left to right, while flipud() will flip each 2D slice up to down.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


---
The array_split() method in NumPy is a useful function for dividing an array into multiple sub-arrays. It provides a flexible way to split arrays along a specified axis, and it can handle cases where the array does not divide evenly.

Functionality of array_split()
ary: The input array to be split.
indices_or_sections: This parameter specifies either the number of equal sections to create or the specific indices at which to split the array.
axis: The axis along which to split the array (default is 0, which means splitting along rows for 2D arrays).
How array_split() Works
Even Splits: If the array can be evenly divided by the specified number of sections, array_split() will return an equal number of sub-arrays.

Uneven Splits: If the array cannot be evenly divided, array_split() handles the situation by distributing the remaining elements across the resulting sub-arrays. This means that some sub-arrays may contain one more element than others.

Key Points
Handles Uneven Sizes: When the total number of elements is not divisible by the number of desired sections, array_split() will distribute the elements as evenly as possible. Some sub-arrays may have one more element than others.

Versatile with Different Dimensions: array_split() can also work with 2D and higher-dimensional arrays, splitting them along the specified axis while maintaining the shape of the sub-arrays.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?


---

Vectorization and broadcasting are two key concepts in NumPy that significantly enhance the efficiency of array operations. Here’s an explanation of both concepts and how they contribute to efficient computation.

1. Vectorization
Definition: Vectorization refers to the process of implementing operations on entire arrays instead of using explicit loops. In essence, it allows for applying mathematical operations to all elements in an array in a single operation.

Benefits:

Performance Improvement: Vectorized operations are executed at a lower level (often in C) and are optimized for speed. This leads to significant performance gains compared to using Python loops, which involve more overhead.
Cleaner Code: Vectorized code is usually more concise and easier to read, reducing the complexity of array manipulations.
2. Broadcasting
Definition: Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes. It automatically expands the smaller array across the larger array in a compatible way.

How it Works: Broadcasting follows a set of rules to determine how to stretch the dimensions of the smaller array to match those of the larger array:

If the arrays have a different number of dimensions, the smaller array is padded with ones on the left side until they match in dimension.
The two arrays are compatible when, for each dimension, the sizes are either the same or one of them is 1.
The smaller array is virtually expanded to match the shape of the larger array, allowing for element-wise operations.
Benefits:

Flexibility: Broadcasting allows for operations between arrays of different shapes, reducing the need for explicit resizing or reshaping of data.
Memory Efficiency: Broadcasting avoids the need to create large temporary arrays in memory, as it operates on the original shapes of the arrays.

# **Practical Questions:**

In [3]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
import numpy as np
# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)
# Interchange rows and columns
interchanged_arr = arr.T
print("\nInterchanged Array:")
print(interchanged_arr)

Original Array:
[[ 94 100  43]
 [ 65  82  87]
 [ 42  59  11]]

Interchanged Array:
[[ 94  65  42]
 [100  82  59]
 [ 43  87  11]]


In [4]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
import numpy as np
# Generate a 1D NumPy array with 10 elements
arr = np.arange(10)
print("Original 1D Array:")
print
# Reshape it into a 2x5 array
reshaped_arr1 = arr.reshape(2, 5)
print("\nReshaped 2x5 Array:")
print(reshaped_arr1)
# Reshape it into a 5x2 array
reshaped_arr2 = arr.reshape(5, 2)
print("\nReshaped 5x2 Array:")
print(reshaped_arr2)


Original 1D Array:

Reshaped 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Create a 4x4 array with random float values
original_array = np.random.rand(4, 4)

# Print the original array
print("Original 4x4 Array:")
print(original_array)

# Add a border of zeros around the array
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 Array with Border of Zeros:")
print(bordered_array)



Original 4x4 Array:
[[0.19466082 0.97824447 0.38595184 0.01815138]
 [0.75167552 0.23268516 0.99889949 0.02109805]
 [0.359877   0.15440452 0.38086485 0.29682301]
 [0.51571653 0.24681776 0.24194545 0.2754162 ]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.19466082 0.97824447 0.38595184 0.01815138 0.        ]
 [0.         0.75167552 0.23268516 0.99889949 0.02109805 0.        ]
 [0.         0.359877   0.15440452 0.38086485 0.29682301 0.        ]
 [0.         0.51571653 0.24681776 0.24194545 0.2754162  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Print the resulting array
print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [7]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)

# Print the results
print("Original Array:")
print(array)
print("\nUppercase Transformation:")
print(uppercase_array)
print("\nLowercase Transformation:")
print(lowercase_array)
print("\nTitle Case Transformation:")
print(titlecase_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']


In [8]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

# Print the resulting array
print("Original Array of Words:")
print(words)
print("\nArray with Spaces Between Characters:")
print(spaced_words)


Original Array of Words:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


In [9]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr_add = arr1 + arr2
arr_sub = arr1 - arr2
arr_mul = arr1 * arr2
arr_div = arr1 / arr2
print(arr_add)
print(arr_sub)
print(arr_mul)
print(arr_div)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [10]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("Identity Matrix:")
print(identity_matrix)
# Extract the diagonal Elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [11]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Print the results
print("Random Integers Array:")
print(random_integers)
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[346 631 441 918 608 956 265 115 154 408 253 298  21  24 914 968 812 930
 801 900 709  34 914 837 253 440 878 914 856 391 882 653 222  39 779 979
 419  30 691 935 997 747  52  96 156 646 262 395 945 948 579 188 162 700
 710 759 409 208 103 158 637 456  17 345 781 177 307  22 552 636 771 999
 446 773 479 282 872 119 696 966 929  44 405 264 665 982 935 141 852 274
 260 653 354 595 198 288 853 277 232 169]

Prime Numbers in the Array:
[631, 709, 653, 419, 691, 997, 409, 103, 17, 307, 773, 479, 929, 653, 853, 277]


In [12]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages
import numpy as np

# Create a NumPy array representing daily temperatures for a month
temperatures = np.array([72, 73, 74, 75, 76, 77, 78,
                         79, 80, 81, 82, 83, 84, 85, 86,
                         87, 88, 89, 90, 91, 92, 93, 94, 95,
                         96, 97, 98, 99, 100, 101, 102, 103,
                         104, 105, 106, 107, 108, 109, 110, 111,
                         112, 113, 114, 115, 116, 117, 118, 119, 120])

# Calculate the number of days in a week
days_in_week = 7

# Calculate the number of weeks in the month
weeks_in_month = len(temperatures) // days_in_week

# Reshape the temperature array into weeks
weekly_temperatures = temperatures.reshape(weeks_in_month, days_in_week)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the weekly averages
print("Weekly Averages:")
for i, avg_temp in enumerate(weekly_averages):
    print(f"Week {i + 1}: {avg_temp:.2f}°F")


Weekly Averages:
Week 1: 75.00°F
Week 2: 82.00°F
Week 3: 89.00°F
Week 4: 96.00°F
Week 5: 103.00°F
Week 6: 110.00°F
Week 7: 117.00°F
